var unlocks = [
    {
        id: "tmp",
        name: "template",
        cost: new Decimal(0),
        costtype: "point",
        description: "this is an upgrade",
        pointreq: new Decimal(0),
        timereq: new Decimal(0),
        unlockreq: ["template"],
    },
    {
        id: "boost",
        name: "Boost",
        cost: new Decimal(1000),
        costtype: "point",
        description: "Using hard work and sweat, unlock the boosting system.",
        pointreq: new Decimal(500),
    },
    {
        id: "metagen",
        name: "MetaGeneration",
        cost: new Decimal(1e7),
        costtype: "point",
        description: "While pondering the fractal geometry of the world, you realize that exponential growth might be able to do you some good. This unlocks a module where you can change the focus of your machines.",
        pointreq: new Decimal(1e5),
    },
    {
        id: "unboost",
        name: "Unboost",
        cost: new Decimal(180),
        costtype: "time",
        description: "Your lapse in clicking has revealed something extraordinary...<br><br>Your boost seems to be collecting some sort of ethereal energy while you let it rest.",
        timereq: new Decimal(45),
        unlockreq: ["boost"],
    },
    {
        id: "boostdelay",
        name: "Sticky Key",
        cost: new Decimal(5e9),
        costtype: "point",
        description: "As you press the boost button, you figure that the maximum boost must be useful for something more than just stopping you. You draw up plans for a machine that will use glue to make the boost degrade slower, powered by your maximum boost.",
        pointreq: new Decimal(5e7),
        unlockreq: ["boost"],
    },
    {
        id: "statis",
        name: "Statis Capacitor",
        cost: new Decimal(1e15),
        costtype: "point",
        description: "You notice the ethereal patterns of energy permeating the infused point button seem to repeat over time. You watch this for hours on end and realize that your button press feel more... powerful at certain times. Certain that this must mean something, you draw up plans for a machine that will track these patterns and use that information to keep your boost stronger over time.",
        pointreq: new Decimal(1e10),
        unlockreq: ["unboost"],
    },
]