var unlocks = [
    {
        id: "tmp",
        name: "template",
        cost: new Decimal(0),
        costtype: "point",
        description: "this is an upgrade",
        pointreq: new Decimal(0),
        timereq: new Decimal(0),
        unlockreq: ["template"],
    },
    {
        id: "boost",
        name: "Boost",
        cost: new Decimal(1000),
        costtype: "point",
        description: "Using hard work and sweat, unlock the boosting system.",
        pointreq: new Decimal(500),
    },
    {
        id: "metagen",
        name: "MetaGeneration",
        cost: new Decimal(1e7),
        costtype: "point",
        description: "While pondering the fractal geometry of the world, you realize that exponential growth might be able to do you some good. This unlocks a module where you can change the focus of your machines.",
        pointreq: new Decimal(1e5),
    },
    {
        id: "unboost",
        name: "Unboost",
        cost: new Decimal(180),
        costtype: "time",
        description: "Your lapse in clicking has revealed something extraordinary...<br><br>Your boost seems to be collecting some sort of ethereal energy while you let it rest.",
        timereq: new Decimal(45),
        unlockreq: ["boost"],
    },
    {
        id: "boostdelay",
        name: "Sticky Key",
        cost: new Decimal(5e9),
        costtype: "point",
        description: "As you press the boost button, you figure that the maximum boost must be useful for something more than just stopping you. You draw up plans for a machine that will use glue to make the boost degrade slower, powered by your maximum boost.",
        pointreq: new Decimal(5e7),
        unlockreq: ["boost"],
    },
    {
        id: "statis",
        name: "Statis Capacitor",
        cost: new Decimal(1e15),
        costtype: "point",
        description: "You notice the ethereal patterns of energy permeating the infused point button seem to repeat over time. You watch this for hours on end and realize that your button press feel more... powerful at certain times. Certain that this must mean something, you draw up plans for a machine that will track these patterns and use that information to keep your boost stronger over time.",
        pointreq: new Decimal(1e10),
        unlockreq: ["unboost"],
    },
    {
        id: "remember",
        name: "Remember the Past",
        cost: new Decimal(300),
        costtype: "time",
        description: "As you watch the ethereal energy of the point button moving for who knows how long, you realize that they patterns tend to repeat. You determine that by using information you've gathered to 'predict' the patterns of the energy, you can speed up the unboost time.",
        timereq: new Decimal(120),
        unlockreq: ["unboost", "statis"],
    },
    {
        id: "metagencheck",
        name: "Check the Metageneration",
        cost: new Decimal(1e20),
        costtype: "point",
        description: "You gulp to yourself as your realize you forgot to multiply the metageneration by your boost. Better fix that.",
        pointreq: new Decimal(1e17),
        unlockreq: ["boost", "template"],
    },
    {
        id: "sun",
        name: "Touch the Sun",
        cost: new Decimal(600),
        costtype: "time",
        description: "While working on the boost channel, you trip over something and knock yourself out. When you awake, a magnificent light floats before your eyes. Staring into the light of eternity, you know there is no true obstacle in what you face now. The ethereal energy wraps through your mind and increases the power to the metageneration system.",
        timereq: new Decimal(120),
        unlockreq: ["remember", "template"],
    },
    {
        id: "hyper",
        name: "Hypertension",
        cost: new Decimal(1e25),
        costtype: "point",
        description: "",
        pointreq: new Decimal(5e21),
        unlockreq: ["statis", "template"],
    },
    {
        id: "statistime",
        name: "Cross-Discipline StatiConfluxi Generation Project",
        cost: new Decimal(450),
        costtype: "time",
        description: "At one point while you relax watching the statis chamber, you realize that you havent tried channeling the power of unboosted time into it, while it has worked so well elsewhere.",
        pointreq: new Decimal(1e17),
        unlockreq: ["statis", "unboost"],
    },
]